// Regenerate the TSL functions from the existing, reviewed GLSL effects.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import Transpiler from 'three/addons/transpiler/Transpiler.js';
import GLSLDecoder from 'three/addons/transpiler/GLSLDecoder.js';
import TSLEncoder from 'three/addons/transpiler/TSLEncoder.js';
const root = new URL('../', import.meta.url);
const renderer = readFileSync(new URL('lib/flight/renderer.ts', root), 'utf8');
const cloud = readFileSync(new URL('lib/flight/clouds.ts', root), 'utf8');
const entries = {
  stone: readFileSync(
    new URL('lib/flight/stone-material.ts', root),
    'utf8',
  ).match(/stoneFragment = `([^`]+)`/)[1],
  halo: renderer.match(/const atmosphereFragment = `([^`]+)`/)[1],
  atmosphere: renderer.match(/const planetAtmosphereFragment = `([^`]+)`/)[1],
  ring: renderer.match(/const ringFragment = `([^`]+)`/)[1],
  sky: renderer.match(
    /fragmentShader: `(varying vec3 v;uniform float air;[^`]+)`/,
  )[1],
  'cloud-volume': readFileSync(
    new URL('lib/flight/cloud-volume.ts', root),
    'utf8',
  ).match(/cloudVolumeFragment = `([^`]+)`/)[1],
  cloud: cloud.match(/fragmentShader: `([^`]+)`/)[1],
};
for (const [name, fragment] of Object.entries(entries)) {
  const parameters = [];
  let source = fragment.replace(
    /varying\s+(\w+)\s+(\w+)\s*;/g,
    (_, type, name) => {
      parameters.push(`${type} ${name}`);
      return '';
    },
  );
  source = source
    .replace(/#include\s+<[^>]+>/g, '')
    .replace(/void main\s*\(\s*\)/, `vec4 shade(${parameters.join(',')})`)
    .replace('gl_FragColor=', 'return ');
  const encoder = new TSLEncoder();
  encoder.reference = true;
  let code = new Transpiler(new GLSLDecoder(), encoder).parse(source);
  let imports = code.match(/^import .*$/gm).join('\n');
  // Texture references do not expose sample(); these atlases are immutable.
  if (code.includes("'texture', uniforms")) {
    imports += "\nimport { texture } from 'three/tsl';";
    code = code.replace(
      /reference\( 'value', 'texture', uniforms\[ '([^']+)' \] \)/g,
      (_, name) => `texture(uniforms['${name}'].value)`,
    );
  }
  code = code
    .replace(/^import .*\n/gm, '')
    .replace(/^\/\/ Three[^\n]*\n/, '')
    .replaceAll('export const ', 'const ')
    .replace(/}, \{[^}]+\} \);/g, '} );');
  // GLSL vec3 uniforms can be Three Color objects; WebGPU must upload RGB, not XYZ.
  code = code.replace(
    /reference\( 'value', 'vec3', uniforms\[ '([^']+)' \] \)/g,
    (_, name) =>
      `reference( 'value', uniforms['${name}'].value.isColor ? 'color' : 'vec3', uniforms['${name}'] )`,
  );
  writeFileSync(
    new URL(`lib/flight/gpu/${name}.js`, root),
    `// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.\n${imports}\n/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */\nexport function createShader(${name === 'ring' ? '_uniforms' : 'uniforms'}) {\n${code}\nreturn shade;\n}\n`,
  );
}

execFileSync(
  'node_modules/.bin/oxfmt',
  Object.keys(entries).map((name) => `lib/flight/gpu/${name}.js`),
  { cwd: root },
);
