// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  reference,
  normalize,
  dot,
  max,
  smoothstep,
  abs,
  sub,
  pow,
  vec3,
  mix,
  add,
  vec4,
  Fn,
} from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(uniforms) {
  const color = reference(
    'value',
    uniforms['color'].value.isColor ? 'color' : 'vec3',
    uniforms['color'],
  );
  const keyDirection = reference(
    'value',
    uniforms['keyDirection'].value.isColor ? 'color' : 'vec3',
    uniforms['keyDirection'],
  );
  const secondaryDirection = reference(
    'value',
    uniforms['secondaryDirection'].value.isColor ? 'color' : 'vec3',
    uniforms['secondaryDirection'],
  );

  const shade = /*@__PURE__*/ Fn(([vRadial, vNormal, vPosition]) => {
    const sunlight = max(
      dot(normalize(vRadial), keyDirection),
      dot(normalize(vRadial), secondaryDirection),
    );
    const day = smoothstep(-0.18, 0.35, sunlight);
    const rim = pow(
      max(
        0,
        sub(1, abs(dot(normalize(vNormal), normalize(vPosition.negate())))),
      ),
      3,
    );
    const tint = mix(vec3(0.22, 0.045, 0.3), color, day);

    return vec4(tint, rim.mul(add(0.08, day.mul(0.6))));
  });

  return shade;
}
