// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  reference,
  mod,
  floor,
  vec2,
  Fn,
  min,
  step,
  max,
  clamp,
  fract,
  mix,
  normalize,
  sign,
  vec3,
  div,
  select,
  dot,
  sin,
  float,
  Break,
  If,
  length,
  sub,
  exp,
  mul,
  add,
  pow,
  Loop,
  vec4,
} from 'three/tsl';
import { texture } from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(uniforms) {
  const bankDensity = texture(uniforms['bankDensity'].value);
  const bankResolution = reference(
    'value',
    'float',
    uniforms['bankResolution'],
  );
  const bankVariant = reference('value', 'float', uniforms['bankVariant']);
  const bankEye = reference(
    'value',
    uniforms['bankEye'].value.isColor ? 'color' : 'vec3',
    uniforms['bankEye'],
  );
  const bankSun = reference(
    'value',
    uniforms['bankSun'].value.isColor ? 'color' : 'vec3',
    uniforms['bankSun'],
  );
  const bankScale = reference(
    'value',
    uniforms['bankScale'].value.isColor ? 'color' : 'vec3',
    uniforms['bankScale'],
  );
  const bankDay = reference('value', 'float', uniforms['bankDay']);
  const bankDetail = reference('value', 'float', uniforms['bankDetail']);

  const bankSlice = /*@__PURE__*/ Fn(([p, slice]) => {
    const tile = vec2(
      mod(slice, 8),
      floor(slice.div(8)).add(bankVariant.mul(bankResolution).div(8)),
    );

    return bankDensity.sample(
      tile
        .mul(bankResolution)
        .add(p.xy.mul(bankResolution.sub(1)))
        .add(0.5)
        .div(
          vec2(
            bankResolution.mul(8),
            bankResolution.mul(bankResolution).div(2),
          ),
        ),
    );
  });

  const bankField = /*@__PURE__*/ Fn(([point]) => {
    const p = point.mul(0.5).add(0.5);
    const inside = step(0, min(p.x, min(p.y, p.z))).mul(
      step(max(p.x, max(p.y, p.z)), 1),
    );
    p.assign(clamp(p, 0, 1));
    const slice = p.z.mul(bankResolution.sub(1));

    return mix(
      bankSlice(p, floor(slice)),
      bankSlice(p, min(bankResolution.sub(1), floor(slice).add(1))),
      fract(slice),
    ).mul(inside);
  });

  const shade = /*@__PURE__*/ Fn(([bankPoint]) => {
    const ray = normalize(bankPoint.sub(bankEye));
    const reciprocal = div(
      1,
      ray.add(sign(ray).mul(0.000001)).add(vec3(0.00000001)),
    );
    const a = vec3(1).negate().sub(bankEye).mul(reciprocal);
    const b = vec3(1).sub(bankEye).mul(reciprocal);
    const lo = min(a, b),
      hi = max(a, b);
    const start = max(0, max(lo.x, max(lo.y, lo.z)));
    const end = min(hi.x, min(hi.y, hi.z));
    const steps = select(bankDetail.greaterThan(0.5), 32, 16);
    const stride = max(0, end.sub(start)).div(steps);
    const jitter = fract(
      sin(dot(bankPoint.xy, vec2(1271.1, 3117.7))).mul(43758.5453),
    );
    const transmission = float(1);
    const radiance = vec3(0);

    Loop(32, ({ i }) => {
      If(
        float(i).greaterThanEqual(steps).or(transmission.lessThan(0.015)),
        () => {
          Break();
        },
      );

      const p = bankEye.add(
        ray.mul(start.add(float(i).add(jitter).mul(stride))),
      );
      const field = bankField(p);
      const mass = field.r;

      If(mass.greaterThan(0.001), () => {
        const gradient = field.gba.mul(2).sub(1).div(bankScale);
        const normal = gradient.div(max(0.035, length(gradient)));
        const wrap = clamp(dot(normal, bankSun).mul(0.6).add(0.4), 0, 1);
        const lightMass = mass.mul(sub(1, wrap));

        If(bankDetail.greaterThan(0.5), () => {
          lightMass.assign(bankField(p.add(bankSun.div(bankScale).mul(1.4))).r);
        });

        const lighting = add(
          0.12,
          exp(lightMass.negate().mul(2.2)).mul(add(0.45, mul(0.55, wrap))),
        );
        const forward = pow(max(0, dot(ray, bankSun)), 6);
        const ambient = mix(
          vec3(0.025, 0.034, 0.065),
          vec3(0.24, 0.33, 0.49),
          bankDay,
        );
        const color = ambient.add(
          vec3(1.28, 1.1, 0.88)
            .mul(bankDay)
            .mul(lighting.mul(0.85).add(forward.mul(0.18))),
        );
        const opacity = sub(1, exp(mass.negate().mul(stride).mul(14)));
        radiance.addAssign(transmission.mul(opacity).mul(color));
        transmission.mulAssign(sub(1, opacity));
      });
    });

    const alpha = sub(1, transmission);

    return vec4(radiance.div(max(0.0001, alpha)), alpha);
  });

  return shade;
}
