// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  reference,
  fract,
  dot,
  Fn,
  floor,
  mul,
  sub,
  vec3,
  mix,
  normalize,
  select,
  smoothstep,
  max,
  add,
  length,
  vec4,
} from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(uniforms) {
  const time = reference('value', 'float', uniforms['time']);
  const seed = reference('value', 'float', uniforms['seed']);
  const coverage = reference('value', 'float', uniforms['coverage']);
  const detail = reference('value', 'float', uniforms['detail']);
  const tint = reference(
    'value',
    uniforms['tint'].value.isColor ? 'color' : 'vec3',
    uniforms['tint'],
  );
  const keyDirection = reference(
    'value',
    uniforms['keyDirection'].value.isColor ? 'color' : 'vec3',
    uniforms['keyDirection'],
  );
  const secondaryDirection = reference(
    'value',
    uniforms['secondaryDirection'].value.isColor ? 'color' : 'vec3',
    uniforms['secondaryDirection'],
  );

  const cloudHash = /*@__PURE__*/ Fn(([p_immutable]) => {
    const p = p_immutable.toVar();
    p.assign(fract(p.mul(0.1031).add(seed.mul(0.003))));
    p.addAssign(dot(p, p.yzx.add(33.33)));

    return fract(p.x.add(p.y).mul(p.z));
  });

  const cloudNoise = /*@__PURE__*/ Fn(([p]) => {
    const i = floor(p),
      f = fract(p);
    f.assign(f.mul(f).mul(sub(3, mul(2, f))));

    return mix(
      mix(
        mix(cloudHash(i), cloudHash(i.add(vec3(1, 0, 0))), f.x),
        mix(
          cloudHash(i.add(vec3(0, 1, 0))),
          cloudHash(i.add(vec3(1, 1, 0))),
          f.x,
        ),
        f.y,
      ),
      mix(
        mix(
          cloudHash(i.add(vec3(0, 0, 1))),
          cloudHash(i.add(vec3(1, 0, 1))),
          f.x,
        ),
        mix(
          cloudHash(i.add(vec3(0, 1, 1))),
          cloudHash(i.add(vec3(1, 1, 1))),
          f.x,
        ),
        f.y,
      ),
      f.z,
    );
  });

  const shade = /*@__PURE__*/ Fn(([cloudDirection, cloudView]) => {
    const radial = normalize(cloudDirection);
    const p = radial.mul(145).add(vec3(time.mul(0.0006), 0, time.mul(0.00022)));
    const field = cloudNoise(p)
      .mul(0.62)
      .add(cloudNoise(p.mul(2.7)).mul(0.26));
    field.addAssign(
      select(detail.greaterThan(0.5), cloudNoise(p.mul(7)).mul(0.12), 0.06),
    );
    const mass = smoothstep(coverage, coverage.add(0.14), field);
    const light = smoothstep(
      -0.18,
      0.5,
      max(dot(radial, keyDirection), dot(radial, secondaryDirection)),
    );
    const color = mix(vec3(0.025, 0.025, 0.06), tint, light).mul(
      add(0.75, field.mul(0.35)),
    );
    const closeFade = smoothstep(0.15, 1.5, length(cloudView));

    return vec4(color, mass.mul(0.83).mul(closeFade));
  });

  return shade;
}
