// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  reference,
  fract,
  dot,
  Fn,
  floor,
  mul,
  sub,
  vec3,
  mix,
  smoothstep,
  normalize,
  dFdx,
  length,
  dFdy,
  max,
  select,
  add,
  clamp,
  vec4,
} from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(uniforms) {
  const time = reference('value', 'float', uniforms['time']);
  const seed = reference('value', 'float', uniforms['seed']);
  const coverage = reference('value', 'float', uniforms['coverage']);
  const detail = reference('value', 'float', uniforms['detail']);
  const coast = reference('value', 'float', uniforms['coast']);
  const coastUp = reference(
    'value',
    uniforms['coastUp'].value.isColor ? 'color' : 'vec3',
    uniforms['coastUp'],
  );
  const tint = reference(
    'value',
    uniforms['tint'].value.isColor ? 'color' : 'vec3',
    uniforms['tint'],
  );
  const keyDirection = reference(
    'value',
    uniforms['keyDirection'].value.isColor ? 'color' : 'vec3',
    uniforms['keyDirection'],
  );
  const secondaryDirection = reference(
    'value',
    uniforms['secondaryDirection'].value.isColor ? 'color' : 'vec3',
    uniforms['secondaryDirection'],
  );

  const cloudHash = /*@__PURE__*/ Fn(([p_immutable]) => {
    const p = p_immutable.toVar();
    p.assign(fract(p.mul(0.1031).add(seed.mul(0.003))));
    p.addAssign(dot(p, p.yzx.add(33.33)));

    return fract(p.x.add(p.y).mul(p.z));
  });

  const cloudNoise = /*@__PURE__*/ Fn(([p]) => {
    const i = floor(p),
      f = fract(p);
    f.assign(f.mul(f).mul(sub(3, mul(2, f))));

    return mix(
      mix(
        mix(cloudHash(i), cloudHash(i.add(vec3(1, 0, 0))), f.x),
        mix(
          cloudHash(i.add(vec3(0, 1, 0))),
          cloudHash(i.add(vec3(1, 1, 0))),
          f.x,
        ),
        f.y,
      ),
      mix(
        mix(
          cloudHash(i.add(vec3(0, 0, 1))),
          cloudHash(i.add(vec3(1, 0, 1))),
          f.x,
        ),
        mix(
          cloudHash(i.add(vec3(0, 1, 1))),
          cloudHash(i.add(vec3(1, 1, 1))),
          f.x,
        ),
        f.y,
      ),
      f.z,
    );
  });

  const filteredCloud = /*@__PURE__*/ Fn(([p, footprint]) => {
    return mix(cloudNoise(p), 0.5, smoothstep(0.35, 1.25, footprint));
  });

  const shade = /*@__PURE__*/ Fn(([cloudDirection, cloudView]) => {
    const radial = normalize(cloudDirection);
    const p = radial.mul(10).add(vec3(time.mul(0.0006), 0, time.mul(0.00022)));
    const footprint = max(length(dFdx(p)), length(dFdy(p)));
    const base = filteredCloud(p, footprint);
    const field = base
      .mul(0.68)
      .add(filteredCloud(p.mul(2.7), footprint.mul(2.7)).mul(0.24))
      .add(
        select(
          detail.greaterThan(0.5),
          filteredCloud(p.mul(7), footprint.mul(7)).mul(0.08),
          0.04,
        ),
      );
    const mass = smoothstep(coverage.sub(0.025), coverage.add(0.2), field);
    mass.mulAssign(
      sub(1, coast.mul(smoothstep(0.98, 0.995, dot(radial, coastUp)))),
    );
    const light = smoothstep(
      -0.18,
      0.5,
      max(dot(radial, keyDirection), dot(radial, secondaryDirection)),
    );
    const sun = normalize(keyDirection.add(secondaryDirection.mul(0.25)));
    const towardSun = filteredCloud(p.add(sun.mul(0.65)), footprint);
    const relief = clamp(add(0.5, base.sub(towardSun).mul(2.3)), 0, 1);
    const thickness = smoothstep(coverage, coverage.add(0.24), field);
    const shade = mix(vec3(0.32, 0.4, 0.56), tint, relief.mul(0.75).add(0.2));
    const color = mix(vec3(0.025, 0.03, 0.065), shade, light);
    color.addAssign(
      vec3(0.28, 0.19, 0.09).mul(light).mul(sub(1, thickness)).mul(mass),
    );
    const closeFade = smoothstep(0.15, 1.5, length(cloudView));

    return vec4(color, mass.mul(0.78).mul(closeFade));
  });

  return shade;
}
