// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  reference,
  normalize,
  dot,
  abs,
  sub,
  max,
  pow,
  vec4,
  Fn,
} from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(uniforms) {
  const color = reference(
    'value',
    uniforms['color'].value.isColor ? 'color' : 'vec3',
    uniforms['color'],
  );

  const shade = /*@__PURE__*/ Fn(([vNormal, vPosition]) => {
    const rim = pow(
      max(
        0,
        sub(1, abs(dot(normalize(vNormal), normalize(vPosition.negate())))),
      ),
      3,
    );

    return vec4(color, rim.mul(0.52));
  });

  return shade;
}
