// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  sin,
  mul,
  add,
  pow,
  fwidth,
  sqrt,
  smoothstep,
  mix,
  Fn,
  sub,
  vec3,
  vec4,
} from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(_uniforms) {
  const ringBand = /*@__PURE__*/ Fn(([r, frequency, power, average]) => {
    const phase = r.mul(frequency);
    const detail = pow(add(0.5, mul(0.5, sin(phase))), power);

    return mix(
      detail,
      average,
      smoothstep(0.15, 0.8, fwidth(phase).mul(sqrt(power))),
    );
  });

  const shade = /*@__PURE__*/ Fn(([vUv]) => {
    const r = vUv.x;
    const bands = ringBand(r, 280, 5, 0.24609375)
      .mul(0.3)
      .add(ringBand(r, 97, 12, 0.16118026).mul(0.55))
      .add(ringBand(r, 21, 2, 0.375).mul(0.12))
      .add(0.03);
    const fade = smoothstep(0, 0.08, r).mul(sub(1, smoothstep(0.9, 1, r)));
    const col = mix(vec3(0.23, 0.015, 0.2), vec3(0.95, 0.055, 0.54), bands);

    return vec4(col.mul(1.4), bands.mul(fade).mul(0.8));
  });

  return shade;
}
