// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  sin,
  mul,
  add,
  pow,
  smoothstep,
  sub,
  vec3,
  mix,
  vec4,
  Fn,
} from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(_uniforms) {
  const shade = /*@__PURE__*/ Fn(([vUv]) => {
    const r = vUv.x;
    const bands = pow(add(0.5, mul(0.5, sin(r.mul(280)))), 5)
      .mul(0.3)
      .add(pow(add(0.5, mul(0.5, sin(r.mul(97)))), 12).mul(0.55))
      .add(0.06);
    const fade = smoothstep(0, 0.08, r).mul(sub(1, smoothstep(0.9, 1, r)));
    const col = mix(vec3(0.23, 0.015, 0.2), vec3(0.95, 0.055, 0.54), bands);

    return vec4(col.mul(1.4), bands.mul(fade).mul(0.8));
  });

  return shade;
}
