// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  reference,
  vec3,
  dot,
  sin,
  fract,
  Fn,
  floor,
  mul,
  sub,
  mix,
  normalize,
  exp,
  pow,
  smoothstep,
  abs,
  max,
  vec4,
} from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(uniforms) {
  const air = reference('value', 'float', uniforms['air']);
  const surfaceUp = reference(
    'value',
    uniforms['surfaceUp'].value.isColor ? 'color' : 'vec3',
    uniforms['surfaceUp'],
  );
  const horizonColor = reference(
    'value',
    uniforms['horizonColor'].value.isColor ? 'color' : 'vec3',
    uniforms['horizonColor'],
  );
  const zenithColor = reference(
    'value',
    uniforms['zenithColor'].value.isColor ? 'color' : 'vec3',
    uniforms['zenithColor'],
  );
  const sunDirection = reference(
    'value',
    uniforms['sunDirection'].value.isColor ? 'color' : 'vec3',
    uniforms['sunDirection'],
  );
  const daylight = reference('value', 'float', uniforms['daylight']);

  const hash = /*@__PURE__*/ Fn(([p]) => {
    return fract(sin(dot(p, vec3(127.1, 311.7, 74.7))).mul(43758.5453));
  });

  const n = /*@__PURE__*/ Fn(([p]) => {
    const i = floor(p),
      f = fract(p);
    f.assign(f.mul(f).mul(sub(3, mul(2, f))));

    return mix(
      mix(
        mix(hash(i), hash(i.add(vec3(1, 0, 0))), f.x),
        mix(hash(i.add(vec3(0, 1, 0))), hash(i.add(vec3(1, 1, 0))), f.x),
        f.y,
      ),
      mix(
        mix(hash(i.add(vec3(0, 0, 1))), hash(i.add(vec3(1, 0, 1))), f.x),
        mix(hash(i.add(vec3(0, 1, 1))), hash(i.add(vec3(1, 1, 1))), f.x),
        f.y,
      ),
      f.z,
    );
  });

  const shade = /*@__PURE__*/ Fn(([v]) => {
    const p = normalize(v);
    const cloud = n(p.mul(8))
      .mul(0.6)
      .add(n(p.mul(19)).mul(0.27))
      .add(n(p.mul(48)).mul(0.13));
    const bandCoordinate = p.y
      .add(p.x.mul(0.46))
      .add(sin(p.z.mul(4)).mul(0.16))
      .mul(5);
    const band = exp(bandCoordinate.negate().mul(bandCoordinate));
    const mist = pow(cloud, 3).mul(band);
    const col = mix(
      vec3(0.09, 0.013, 0.16),
      vec3(0.04, 0.22, 0.31),
      smoothstep(0.4, 0.75, cloud),
    );
    const space = vec3(0.001, 0.002, 0.008).add(col.mul(mist).mul(1.5));
    const horizon = pow(max(0, sub(1, abs(dot(p, surfaceUp)))), 3);
    const glow = pow(max(0, dot(p, sunDirection)), 12).mul(daylight);
    const sky = mix(zenithColor, horizonColor, horizon).add(
      vec3(0.18, 0.08, 0.045).mul(glow),
    );

    return vec4(mix(space, sky, air), 1);
  });

  return shade;
}
