// Generated by scripts/port-shaders.mjs. Edit the source GLSL, then regenerate.
import {
  reference,
  Fn,
  normalize,
  abs,
  vec3,
  pow,
  dot,
  max,
  sin,
  fwidth,
  smoothstep,
  sub,
  mul,
  add,
  mix,
  dFdx,
  length,
  dFdy,
  vec4,
} from 'three/tsl';
import { texture } from 'three/tsl';
/** @returns {(...inputs: import('three/webgpu').Node[]) => import('three/webgpu').Node<'vec4'>} */
export function createShader(uniforms) {
  const stoneTexture = texture(uniforms['stoneTexture'].value);
  const stoneAlbedo = texture(uniforms['stoneAlbedo'].value);
  const stoneAlbedoReady = reference(
    'value',
    'float',
    uniforms['stoneAlbedoReady'],
  );

  const stoneField = /*@__PURE__*/ Fn(([p, weight]) => {
    return stoneTexture
      .sample(p.yz)
      .mul(weight.x)
      .add(stoneTexture.sample(p.xz).mul(weight.y))
      .add(stoneTexture.sample(p.xy).mul(weight.z));
  });

  const stoneSlate = /*@__PURE__*/ Fn(([p, weight]) => {
    return stoneAlbedo
      .sample(p.yz)
      .rgb.mul(weight.x)
      .add(stoneAlbedo.sample(p.xz).rgb.mul(weight.y))
      .add(stoneAlbedo.sample(p.xy).rgb.mul(weight.z));
  });

  const shade = /*@__PURE__*/ Fn(([stonePoint, stoneNormal, stonePhase]) => {
    const n = normalize(stoneNormal);
    const weight = pow(abs(n), vec3(4));
    weight.divAssign(max(dot(weight, vec3(1)), 0.0001));
    const grain = stoneField(stonePoint.mul(400).add(stonePhase), weight);
    const slate = stoneSlate(
      stonePoint.mul(416.6666666666667).add(stonePhase),
      weight,
    );
    const bandPhase = stonePoint.y
      .mul(900)
      .add(sin(stonePoint.x.mul(330).add(stonePhase.x.mul(6))).mul(0.7))
      .add(sin(stonePoint.z.mul(260)).mul(0.4));
    const bandFilter = sub(1, smoothstep(0.4, 2, fwidth(bandPhase)));
    const bands = add(0.5, mul(0.5, sin(bandPhase)).mul(bandFilter));
    const dust = smoothstep(0.25, 0.85, n.y).mul(add(0.25, grain.a.mul(0.55)));
    const tone = mix(
      grain.rgb.add(0.25),
      slate.mul(2.1).add(0.38),
      stoneAlbedoReady,
    );
    tone.mulAssign(mix(vec3(0.82, 0.85, 0.93), vec3(1.08, 1.03, 1), bands));
    tone.assign(mix(tone, vec3(1.03, 0.98, 1.01), dust));
    const pixelWorld = max(length(dFdx(stonePoint)), length(dFdy(stonePoint)));
    const relief = mix(grain.a, dot(slate, vec3(0.3333)), stoneAlbedoReady)
      .mul(0.000008)
      .mul(sub(1, dust))
      .mul(sub(1, smoothstep(0.002, 0.009, pixelWorld)));

    return vec4(tone, relief);
  });

  return shade;
}
